[package]
name = "bin_lift"
version = "0.0.1-dev-3"
edition = "2021"


[lib]
name = "zydis2llvmir"
path = "src/lib.rs"

[dependencies]
inkwell = { version = "0.5.0", features = ["llvm18-0", "llvm18-0-prefer-static"]}
thiserror = "2"
zydis = { version = "4.1.1", features = ["default"] }
